version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: livecode-cicd
    env_file:
      - .env 
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:8888"
    networks:
      - db-network
  db:
    image: postgres:latest
    container_name: livecode-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - ${DB_PORT}:5555
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
volumes:
  db-data:
networks:
  db-network: